{% set version = "2.0-8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-polynomf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PolynomF_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PolynomF/PolynomF_{{ version }}.tar.gz
  sha256: 72675174eeb164ea335b49f2995447cd9b4e8662f72c3f5b47e9ffb8413c24f7

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('PolynomF')"           # [not win]
    - "\"%R%\" -e \"library('PolynomF')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=PolynomF
  license: GPL-2.0-only
  summary: Implements univariate polynomial operations in R, including polynomial arithmetic, finding zeros, plotting, and some operations on lists of polynomials.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: PolynomF
# Type: Package
# Title: Polynomials in R
# Description: Implements univariate polynomial operations in R, including polynomial arithmetic, finding zeros, plotting, and some operations on lists of polynomials.
# Version: 2.0-2
# Date: 2019-06-18
# NeedsCompilation: yes
# Imports: stats, Rcpp, methods
# Depends: R (>= 3.0.0), graphics, grDevices
# Author: Bill Venables, with contribution by Kurt Hornik and Georgi Boshnakov
# Maintainer: Bill Venables <Bill.Venables@gmail.com>
# License: GPL-2
# Encoding: UTF-8
# LinkingTo: Rcpp
# RoxygenNote: 6.1.1
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# Packaged: 2019-06-18 06:18:28 UTC; bill
# Repository: CRAN
# Date/Publication: 2019-06-18 06:50:25 UTC
