appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: BBph+AQDSwRp9tYP+Js2+XqMmy96Mjs/NooyEPAze+0wF7klTZOHIkZN+3H7gWd13eApEJvqisUvVmT1l5jsJTGqcraEMyqwl4zdvYjr/fQ/kJ6c1dUOE6cR3ZviktrvIFOYqSLMcKeIHXVj0IqJo3jqPKmEF/yLYa5iMiPS3s92JgeYfluBEHejgL7DHu0PWe8cQXRMP1GXFcH9x294izxJoC0fLrT+w3b4hrYzp+AKOccOp62O5ANAUhIohHck0xnwuc9uJXRsNA29tKwC7NHOMUfGuQdIytaOhm8Edwn4Q1zpYLin+y00t+6Xhr4Ncc7m8G1PX2pn5NeMUVazHAhi12oglcSYDt4jrLvdfIVM6lXcXA2vPHo5+U6R+Wk+lGBYsI50mWqSKLgjfwLCYfgwcUjrlvDhrA9VJRNkCtN7hXvBdSkwdqhQZqqQgB72T0hoCvSszqywBMH5WVyGT/PzCbJUnxP1ugojpRQP2Ky1QbXxJLoD/OQqjE3mqgnPTIX5+LDA5DmCFDBQC1CF/fvE0ZGxO+6pZvOKhngX0j3627mId7NkAFXz2Qy0bnhEe9HtYiPQlLI2L8qN7VwXkgk5sr0/eOvvkY+sX+l0xePi0tfWUld8Y3NupU42bWG6dV11IZP0JIe0p9ninEo4L5Q4cQ8XytE2FTOVI/UE6xc=}
