travis:
  secure:
    BINSTAR_TOKEN: R5ssI/V/Qb4T1emribfqfU4sq5jNI16FRt+cH1c15hika3LJ1i2jlf1KEdnfucKlkQ1aeMemWBAaD52uRZuUV6ijGaThbpWw4E946npmYrEnhaWP9B3sQ8QoV9ifPT2u0YAu94hVH8VaAsy4FE/9woBXRMm1/sJKZR8wIqa6TAxurX0QMMvdL2uc6nN+QLgMfYGUpm3y0ZtgsGJeoK8JqYMZ5Muqg1Bsdz0UbYAjc4vezFNUEdSH7O5e9osOzLLM4QlzfZjfhpvNZlHZmgJSL68LghGKfjzhFeMYw1Ks++LjdVEfpspbSgqZy0E1KGc858BC/LreP6dBRb9K3pl6YWBdSBisIvdGq4y/dcHWIcSC8FLptHaZQXlLr9XM5MCr8yH5zp/SJNTYSMnCOrq35QUlwTnvOpYvCW2gyMgnrHXt+NwhNmApzs3TAJzay8obmxMR+Wsv8XYFaYHB7UKWc0mmQ7j8lIEFL52ckwcsfFlpeFfAKpNiUL0Tzr5j88hB2BUshY6QJeEGwJovFnqoDzbnD/Z8xVWhAc7DkY6I3ze9z+jSuY8xRiZpqO6h5fuGo8JKlnXvvuFRK+phqDQX+KDZoXbhJZrXnGiDgFBWJcXYMG2M8AimOwquFRP+fvLDXDL00w4Eqi09OGpkNc9QlC4bb24gbpKrH953akn8SGE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
